# Generated by Django 4.0.1 on 2022-01-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expensses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=1, null=1)),
                ('text', models.CharField(blank=1, max_length=200, null=1)),
                ('time', models.DateTimeField(blank=1, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=1, null=1)),
                ('text', models.CharField(blank=1, max_length=200, null=1)),
                ('time', models.DateTimeField(blank=1, null=1)),
            ],
        ),
    ]
